task: detection

model: DEIM
criterion: DEIMCriterion
postprocessor: PostProcessor


use_focal_loss: True
eval_spatial_size: [640, 640] # h w
checkpoint_freq: 20    # save freq


DEIM:
  backbone: ExMamba
  encoder: HybridEncoder
  decoder: RTDETRTransformerv2


ViMM:
  in_dim: 3
  embed_dim: [64, 128, 256]
  num_experts: 10
  top_k: 2
  depths: [2,2,2]
  mlp_ratio: 4.
  ssd_expand: 1.
  state_dim: [49,25,9]
  router: 'topk'
  dropout: 0
  shared: True
  filter_radio: 0.3


HybridEncoder:
  in_channels: [128, 256, 256]
  feat_strides: [8, 16, 16]

  # intra
  hidden_dim: 256
  use_encoder_idx: [2]
  num_encoder_layers: 1
  nhead: 8
  dim_feedforward: 1024
  dropout: 0.
  enc_act: 'gelu'

  # cross
  expansion: 1.0
  depth_mult: 1
  act: 'silu'
  version: rt_detrv2


RTDETRTransformerv2:
  feat_channels: [256, 256, 256]
  feat_strides: [8, 16, 16]
  hidden_dim: 256
  num_levels: 3

  num_layers: 6
  num_queries: 300

  num_denoising: 100
  label_noise_ratio: 0.5
  box_noise_scale: 1.0 # 1.0 0.4

  eval_idx: -1

  # NEW
  num_points: [4, 4, 4] # [3,3,3] [2,2,2]
  cross_attn_method: default # default, discrete
  query_select_method: default # default, agnostic


PostProcessor:
  num_top_queries: 300

DEIMCriterion:
  weight_dict: {loss_vfl: 1, loss_bbox: 5, loss_giou: 2,}
  losses: ['vfl', 'boxes', ]
  alpha: 0.75
  gamma: 2.0
  use_uni_set: False

  matcher:
    type: HungarianMatcher
    weight_dict: {cost_class: 2, cost_bbox: 5, cost_giou: 2}
    alpha: 0.25
    gamma: 2.0
