task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

# num_classes: 365
# remap_mscoco_category: False

# num_classes: 91
# remap_mscoco_category: False

num_classes: 11
remap_mscoco_category: False


train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /home/jrf/mamba/data/nwpu/image/train
    ann_file: /home/jrf/mamba/data/nwpu/instances_train.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 4
  drop_last: True
  collate_fn:
    type: BatchImageCollateFunction


val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /home/jrf/mamba/data/nwpu/image/test
    ann_file: /home/jrf/mamba/data/nwpu/instances_test.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 4
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction
